version: '3.8'
services:
  pool-control:
    build: .
    container_name: pool-control
    restart: always
    ports:
      - "3000:3000"
    environment:
      - GATEWAY_URL=${GATEWAY_URL}
      - PORT=3000
      - POLL_INTERVAL=500
